Iter3
RedWood011/ServiceURL pull request #6
Opened 2023-01-18 21:30 UTC by RedWood011

2023-01-23 09:56 UTC, blattaria7 requested changes
Отличная работа!) Мне очень нравится как спроектирована архитектура сервиса и то, как написан код - красиво и лаконично)

Оставила несколько замечаний-рекомендаций, по большей части "косметического характера". Буду ждать фиксов)

2023-01-23 09:56 UTC, blattaria7 commented on internal/tests/auxiliary_test.go
> +func parseRespBody(t *testing.T, body []byte, result interface{}) {
немножко подушню тут: для чего нужны данные методы? (не увидела их использования)

2023-01-23 09:56 UTC, blattaria7 commented on internal/service/url.go
> +func (s *TranslationServer) CreateShortURL(ctx context.Context, urls []entities.URL) (IDs []string, err error) {
возвращаемая переменная не должна быть глобальной, это избыточно

2023-01-23 09:56 UTC, blattaria7 commented on internal/repository/repository.go
> +	default:
ох уж эти преждевременные оптимизации )) не знала, что у нас добавили спойлер про то что в этом проекте будет несколько хранилищ )

можно конечно оставить так, но на будущее лучше так не делать и делать просто return - мы в гошке стараемся писать максимально коротко и просто)

2023-01-23 09:56 UTC, blattaria7 commented on internal/transport/deliveryhttp/helpers.go
> +	//writeErrStatus(ctx, w, http.StatusTeapot)
скажу тут, на примере этих комментов

вообще хорошо бы сделать форматирование по всему проекту, добавив линтеры
они помогают избегать простых ошибок и организуют единый кодстайл приятный глазу каждому гошнику ))
можно попробовать вот этот, он не самый продвинутый, но зато его почти во всех компаниях используют: https://golangci-lint.run/ - можно собрать под него конфиг и запускать его командой, перед тем как коммититься) 

и статейка на эту тему: https://habr.com/ru/post/457970/

2023-01-23 09:56 UTC, blattaria7 commented on cmd/shortener/main.go
> +	httpServer := http.Server{
надо добавить ему таймаут обязательно!

2023-01-23 09:56 UTC, blattaria7 commented on cmd/shortener/main.go
> +	repo := repository.NewRepository("")
на будущее, в таких местах лучше всего для читаемости добавить заглушку или коммент (а то не понятно почему мы пустоту репозиторию передаем)) )

2023-01-23 09:56 UTC, blattaria7 commented on internal/service/url.go
> +	createURLs := make([]entities.URL, len(urls))
тут наверное опечатка, забыли про капасити - `createURLs := make([]entities.URL, 0, len(urls))`

2023-01-23 09:56 UTC, blattaria7 commented on internal/transport/deliveryhttp/helpers.go
> +func writeSuccessful(ctx context.Context, w http.ResponseWriter, code int, payload interface{}) {
зачем мы тут передаем контекст?) (не увидела использования, уточняю)

2023-01-23 09:56 UTC, blattaria7 commented on internal/transport/deliveryhttp/helpers.go
> +func writeSuccessful(ctx context.Context, w http.ResponseWriter, code int, payload interface{}) {
дальше в методах `writeErrStatus` и `writeError` тоже самое

2023-01-23 09:56 UTC, blattaria7 commented on cmd/shortener/main.go
> +			if shutdownCtx.Err() == context.DeadlineExceeded {
тут лучше будет использовать метод `errors.Is`, так как сравнение может сломаться на враппинге

2023-01-23 09:56 UTC, blattaria7 commented on internal/repository/repository.go
> +func NewRepository(db string) service.Storage {
тут на интерфейс ссылается конструктор, а должен на объект)

2023-01-23 09:56 UTC, blattaria7 commented on internal/repository/repository.go
> +func NewRepository(db string) service.Storage {
рекомендую почитать про реализацию утиной типизации в го https://habr.com/ru/post/509868/ )

2023-01-23 09:56 UTC, blattaria7 commented on internal/tests/url_test.go
> +func createShortURL(t *testing.T, fullURL string, router *deliveryhttp.Router) string {
вспомогательные функции должны начинаться с вызова `t.Helper() `

2023-01-23 09:56 UTC, blattaria7 commented on internal/tests/url_test.go
> +package tests
правильнее эти файлы с тестами методов будет положить туда, где лежит их реализация)

2023-01-23 10:01 UTC, RedWood011 commented on internal/tests/url_test.go
> +package tests
Интегротесты обычно лежат в корне проекта. Какой мне смысл класть интегротест, если он работает со всеми слоями сервиса?

2023-01-23 10:02 UTC, RedWood011 commented on internal/transport/deliveryhttp/helpers.go
> +func writeSuccessful(ctx context.Context, w http.ResponseWriter, code int, payload interface{}) {
потому что в дальнейшем захочу добавить логер и у меня есть сразу возможность использовать контекст.

2023-01-23 10:05 UTC, RedWood011 commented on internal/repository/repository.go
> +	default:
спойлеров не было, изначально задумывался, что будет несколько репозиториев для хранения и предусмотрел под это расширение.

2023-01-23 10:06 UTC, RedWood011 commented on internal/service/url.go
> +func (s *TranslationServer) CreateShortURL(ctx context.Context, urls []entities.URL) (IDs []string, err error) {
а с чего вы решили, что эта переменная глобальная? 
Это только ее имя и нигде на уровне пакета она не объявлена.

2023-01-23 10:07 UTC, RedWood011 commented on internal/tests/auxiliary_test.go
> +func parseRespBody(t *testing.T, body []byte, result interface{}) {
Потому что не стал писать интегротест на работу с json. А в целом я сразу сделал возможность добавления множества ссылок через POST метод. Нужно для интегротеста, когда захочу его дописать.

2023-01-23 10:08 UTC, RedWood011 commented on go.mod
> +go 1.18
Использую в работе стабильную версию 1.18 и пока с нее не переезжали. Поэтому решил использовать 1.18 пока что. Не читал новые обновления и что там вышло.

2023-01-23 10:12 UTC, RedWood011 commented on cmd/shortener/main.go
> +			if shutdownCtx.Err() == context.DeadlineExceeded {
Учту

2023-01-23 10:16 UTC, blattaria7 commented on internal/service/url.go
> +func (s *TranslationServer) CreateShortURL(ctx context.Context, urls []entities.URL) (IDs []string, err error) {
Я имела ввиду публичная, не так выразилась
Согласна, это не так критично)

2023-01-23 10:18 UTC, blattaria7 commented on internal/tests/url_test.go
> +package tests
Тогда согласна, можно оставить так)

2023-01-23 10:23 UTC, RedWood011 commented on internal/tests/url_test.go
> +func createShortURL(t *testing.T, fullURL string, router *deliveryhttp.Router) string {
Как часто вы видите, что в проекте все вспомогательные функции помечаются t.Helper() ? 
Это лишь рекомендация чтобы узнать, кто вызывал эту функцию. Но я и так знаю, кто и где вызывает эту функции в какой строке. Поэтому не вижу смысла добавлять его. Потому что он лишь
 сообщит имя файла и номер строки кода откуда был вызван.

2023-01-23 10:30 UTC, RedWood011 commented on internal/transport/deliveryhttp/helpers.go
> +	//writeErrStatus(ctx, w, http.StatusTeapot)
Я и так знаю, что мертвые комментарии не есть хорошо оставлять в коде. И мертвого в коде в проекте присутствие абсолютно не желательно.  Но по причине того, что есть автотесты. Я не стал удалять ответ http.StatusTeapot.  Который бы хотел использовать в дальнейшей. Снова же причина в автотестах.

2023-01-23 10:32 UTC, RedWood011 commented on internal/service/url.go
> +	createURLs := make([]entities.URL, len(urls))
Да опечатка вышла, поправлю

2023-01-23 10:37 UTC, RedWood011 commented on internal/repository/repository.go
> +func NewRepository(db string) service.Storage {
Не вижу проблемы, я возвращаю объект, который реализует интерфейс service.Storage. 
Что не так с утиной типизацией?

2023-01-23 11:54 UTC, RedWood011 commented on cmd/shortener/main.go
> +	httpServer := http.Server{
кому ему? Серверу? Таймауты на что именно? 
ReadTimeout? 	ReadHeaderTimeout? 	WriteTimeout?  IdleTimeout?  
Если речь идет о них изначально не было оговорено никаких таймаутов, а ставить их наобум. Не вижу смысла. Когда в задаче этого не было оговорено. Да и хотелось бы явных example. Если они так нужны, почему именно эти и от чего отталкивались.

2023-01-23 12:02 UTC, RedWood011 commented on cmd/shortener/main.go
> +	repo := repository.NewRepository("")
Согласен, сделаю так

2023-01-24 14:16 UTC, blattaria7 commented on internal/tests/url_test.go
> +func createShortURL(t *testing.T, fullURL string, router *deliveryhttp.Router) string {
Обычно в боевых проектах при сборке перед раскаткой запускается job с линтерами (конкректный набор линтеров обычно зафиксирован как стандарт для всех сервисов) и по лично моему опыту данная вещь была необходима для успешного прохождения job'ы

Но тут таких требований нет, так что можно оставить так)

2023-01-24 14:39 UTC, blattaria7 commented on internal/repository/repository.go
> +func NewRepository(db string) service.Storage {
все, увидела, что методы реализованы корректно)

2023-01-24 14:46 UTC, blattaria7 commented on cmd/shortener/main.go
> +	httpServer := http.Server{
я тут имела ввиду `WriteTimeout`, `ReadTimeout`, обычно их добавляют для запросов (и в будущем они понадобятся для автотестов).
в данном спринте они не нужны. прошу прощения за свою невнимательность, этот тред закрываю.

2023-01-24 15:30 UTC, blattaria7 approved these changes

2023-01-24 16:10 UTC, merged