iter13
RedWood011/ServiceURL pull request #8
Opened 2023-03-01 15:14 UTC by RedWood011

2023-03-02 07:26 UTC, Perederey requested changes
Код стал лучше, чем был!
Но еще требуется доработка 
1) пакет context
2) интерфейсы
3) поправить go vet

2023-03-02 07:26 UTC, Perederey commented on docker-compose.yml
> +version: '3.8'
Отлично! Плюс за docker-compose

2023-03-02 07:26 UTC, Perederey commented on internal/repository/database/postgres_database.go
> +type DB interface {
Тут немного напутал, интерфейс должен быть отдельно и базы и интерфейс должен наследоваться тремя структурами: базой данных,memory и файловым хранилищем

2023-03-02 07:26 UTC, Perederey commented on internal/repository/database/postgres_database.go
> +	ctx := context.Background()
Context нужно передавать в функции, а не создавать внутри Структуры

И я бы тут разделил создание и ping на две функции

2023-03-02 07:26 UTC, Perederey commented on internal/repository/filememory/file_memory.go
> +	cacheShortURL := make(map[string]map[string]string)
Тут что-то перемудрил с логикой

При чтении - читаешь в слайс, при записи записываешь в слайс, а перед этим делаешь приобразование из map и обратно

2023-03-02 07:26 UTC, Perederey commented on internal/repository/filememory/file_memory.go
> +	cacheShortURL := make(map[string]map[string]string)
При этом читаешь при старте и записываешь при остановке приложения данные, а так их звонишь в Мемори.

2023-03-02 07:26 UTC, Perederey commented on internal/repository/memory/url.go
> +func (s *MemoryStorage) CreateShortURLs(ctx context.Context, urls []entities.URL) ([]entities.URL, error) {
Надо сделать :)

2023-03-02 07:26 UTC, Perederey commented on internal/service/storage.go
> +	GetFullURLByID(ctx context.Context, shortURL string) (res string, err error)
Вот этот интерфейс должен только быть, а в DB непонятно зачем тебе он

2023-03-04 17:56 UTC, RedWood011 commented on internal/repository/filememory/file_memory.go
> +	cacheShortURL := make(map[string]map[string]string)
Здесь инициализацию просто. 
Записываю я их и так в слайс файла. Но храню все в мапах. Все же доступ к мапе быстрее, чем доступ к слайсу при его переборе. Инициализацию только дольше. Но на чтении я выиграю по скорости

2023-03-09 20:05 UTC, Perederey approved these changes
давай двигаться дальше, так как тесты работают и все ок)
Но context так кажется пока еще не поддается, возьми 1:1 на нем обсудим 👍 

В трекере ставлю - Нужно переделать, так как чтобы сразу не принять работу, но ничего переделывать не нужно.

2023-03-09 20:05 UTC, Perederey commented on internal/repository/memoryfile/memoryfile.go
> +func (f *FileMap) Ping(ctx context.Context) error {
(_ context.Context) - можно еще вот так указать, чтобы не создавать переменную :)

2023-03-09 20:05 UTC, Perederey commented on internal/repository/memoryfile/memoryfile_test.go
> +				for i := 0; i < len(testCase.want); i++ {
прошллый раз видимо пропустил, но лучше убрать вот эти все condtions из тестов и сделать просто не табличные тесты, а обычные.

2023-03-09 20:05 UTC, Perederey commented on internal/repository/postgres/database.go
> +		ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
вот сюда бы тест и ты увидел, что у тебя context нигде не обрабатывается :)
А зачем тут doWithTries?

2023-03-09 20:05 UTC, Perederey commented on internal/repository/postgres/repeatable.go
> +func doWithTries(fn func() error, attemtps int, delay time.Duration) (err error) {
в целом прикольная штука, но немного оверинжеринг, можно на 1:1 обсудить

2023-03-09 20:22 UTC, merged